dist: xenial   # required for Python >= 3.7
language: python
python:
  - "3.9"
  - "3.10"
# command to install dependencies
install:
  - pip install pdm && pdm install
# command to run tests
script:
  - pytest

