[tool.poetry]
name = "prevenger"
version = "0.0.8"
description = "final commom utils for prevengers"
include = []
authors = [
    "twocucao <twocucao@gmail.com>"
]

readme = 'README.md'

repository = "https://github.com/twocucao/prevengers"
homepage = "https://github.com/twocucao/prevengers"

keywords = ['prevenger']

[[tool.poetry.source]]
name = "douban"
url = 'https://pypi.douban.com/simple/'

[tool.poetry.dependencies]
python = "^3.7"
werkzeug = "*"
requests = "*"
click_didyoumean = "^0.0.3"
crayons = "^0.2.0"
click_completion = "^0.5.1"
sqlalchemy = "*"
aiohttp = "^3.5"
aiofiles = "^0.4.0"
aiodns = "^2.0"
pydantic = "^1.5.1"

[tool.poetry.dev-dependencies]
ipython = "*"
fabric = "*"
gunicorn = "*"
flask = "*"
pycrypto = "*"
pillow = "*"

pandas = "*"

xlsxwriter = "*"
xlwt = "*"
openpyxl = "*"

django = "*"
ipdb = "*"

sphinx = "*"
autoflake = "*"
coverage = "*"
"flake8" = "*"
mypy = "*"

pytest = "*"
pytest-cov = "*"
pytest-html = "*"
pytest-sugar = "*"
sqlalchemy-stubs = "^0.1.0"
pre-commit = "^1.16"


[tool.poetry.scripts]
prevenger-cli = 'prevenger.cli:main'

[tool.black]
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | assets
  | scripts
)/
'''
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"


